seek by decimal keys
mkobayashime/video-stream-shortcuts pull request #99
Opened 2022-11-27 07:07 UTC by yudukikun5120

You will be able to seek videos at MS Streams and TED by pressing the numerical keys: `0-9` with this feature.
I tried to work on Amazon Video, but it did not achieve.

2022-11-27 07:12 UTC, yudukikun5120 commented
@mkobayashime I do not subscribe to DAZN, so could you add snippets below to `dazn.js` and check it if you could?

```js
case "0":
case "1":
case "2":
case "3":
case "4":
case "5":
case "6":
case "7":
case "8":
case "9": {
  if (this.config[`keys-decimal`]) {
    decimalSeek({
      media: this.media,
      numericKey: e.key,
    })
    this.callIndicatorCreator({
      type: "text",
      text: e.key,
    })
  }
  break
}
```

2022-11-28 13:28 UTC, mkobayashime commented
@yudukikun5120 
It's not working in DAZN, and I couldn't find any solution for that.
As for Prime Video I changed a few lines to make this work #100.

2022-11-28 13:30 UTC, mkobayashime requested changes

2022-11-28 13:30 UTC, mkobayashime commented on public/options.html
> +                <span class="key">0-9</span>
```suggestion
                <span class="key">0</span>
                –
                <span class="key">9</span>
```

2022-11-28 13:30 UTC, mkobayashime commented on src/methods/seek.js
> + * @param {number} numericKey - Number key pressed. Must be between 0 and 9
```suggestion
 * @param {string} numericKey - Number key pressed. Must be between 0 and 9
```

Values passed are string actually.

2022-11-28 13:30 UTC, mkobayashime commented on src/methods/seek.js
> +  media.currentTime = media.duration * (numericKey / 10)
```suggestion
  const keyIndex = parseInt(numericKey)
  if (isNaN(keyIndex)) return

  media.currentTime = media.duration * (keyIndex / 10)
```

We should avoid implicit casting.

2022-11-28 13:37 UTC, yudukikun5120 commented on src/methods/seek.js
> + * @param {number} numericKey - Number key pressed. Must be between 0 and 9
How shameful!

2022-11-28 13:41 UTC, yudukikun5120 commented
@mkobayashime I sincerely appreciate the rich change suggestions.

2022-11-28 14:00 UTC, yudukikun5120 commented
@mkobayashime I implemented the codes for Prime Video and asked you for a code review.

2022-11-29 06:18 UTC, mkobayashime commented
@yudukikun5120 
Could you squash misc commits (especially ones simply applying suggestions by me, originally changed in f6d366340dae34d98710498d672d0c8285fb63ee) before I merge them?

2022-11-29 07:23 UTC, yudukikun5120 commented
@mkobayashime It would presumably be better to use _squash and merge_ because it marks the index of PR (e.g., `fix the hoge (#PRIndex)`) on the squashed commit message. Could you try it?

2022-11-29 09:00 UTC, mkobayashime commented
@yudukikun5120 
I suggeted the squashing because I thought you were intending to merge these changes with multiple (not all-in-one) commits per intension, but I can do the _Squash and merge_ if it's OK for you.

2022-11-29 09:05 UTC, yudukikun5120 commented
@mkobayashime I appreciate your thoughtfulness. I'm OK with making it in a single commit.

2022-11-29 13:40 UTC, merged